// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'product_item.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ProductItem _$ProductItemFromJson(Map<String, dynamic> json) => ProductItem(
      id: (json['id'] as num?)?.toInt(),
      appId: (json['appId'] as num?)?.toInt(),
      partnerLogo: json['partnerLogo'] as String?,
      partnerName: json['partnerName'] as String?,
      partnerDescription: json['partnerDescription'] as String?,
      partnerPhone: json['partnerPhone'] as String?,
      partnerApi: json['partnerApi'] as String?,
      type: (json['type'] as num?)?.toInt(),
      secretKey: json['secretKey'] as String?,
      defaultAmount: (json['defaultAmount'] as num?)?.toInt(),
      defaultLoanDays: (json['defaultLoanDays'] as num?)?.toInt(),
      defaultInterestRate: (json['defaultInterestRate'] as num?)?.toDouble(),
      extend: json['extend'] as String?,
      iosDownloadUrl: json['iosDownloadUrl'] as String?,
      androidDownloadUrl: json['androidDownloadUrl'] as String?,
      admittanceUrl: json['admittanceUrl'] as String?,
      credentialStuffingUrl: json['credentialStuffingUrl'] as String?,
      pushUserDataUrl: json['pushUserDataUrl'] as String?,
      creditDataUrl: json['creditDataUrl'] as String?,
      loanProductUrl: json['loanProductUrl'] as String?,
      loanContractUrl: json['loanContractUrl'] as String?,
      submitLoanUrl: json['submitLoanUrl'] as String?,
      loanPreviewUrl: json['loanPreviewUrl'] as String?,
      bankListUrl: json['bankListUrl'] as String?,
      bindBankUrl: json['bindBankUrl'] as String?,
      setDefaultBankUrl: json['setDefaultBankUrl'] as String?,
      preBind: json['preBind'] as String?,
      getBank: json['getBank'] as String?,
      userLoanAmt: json['userLoanAmt'] as String?,
      orderStatusUrl: json['orderStatusUrl'] as String?,
      repayPlanUrl: json['repayPlanUrl'] as String?,
      repayDetailsUrl: json['repayDetailsUrl'] as String?,
      contractSignUrl: json['contractSignUrl'] as String?,
      queryUserUrl: json['queryUserUrl'] as String?,
      status: (json['status'] as num?)?.toInt(),
      isHead: (json['isHead'] as num?)?.toInt(),
      addBank: (json['addBank'] as num?)?.toInt(),
      isSign: (json['isSign'] as num?)?.toInt(),
      isReload: (json['isReload'] as num?)?.toInt(),
      created: (json['created'] as num?)?.toInt(),
      updated: (json['updated'] as num?)?.toInt(),
      businessType: json['businessType'] as String?,
    );

Map<String, dynamic> _$ProductItemToJson(ProductItem instance) =>
    <String, dynamic>{
      'id': instance.id,
      'appId': instance.appId,
      'partnerLogo': instance.partnerLogo,
      'partnerName': instance.partnerName,
      'partnerDescription': instance.partnerDescription,
      'partnerPhone': instance.partnerPhone,
      'partnerApi': instance.partnerApi,
      'type': instance.type,
      'secretKey': instance.secretKey,
      'defaultAmount': instance.defaultAmount,
      'defaultLoanDays': instance.defaultLoanDays,
      'defaultInterestRate': instance.defaultInterestRate,
      'extend': instance.extend,
      'iosDownloadUrl': instance.iosDownloadUrl,
      'androidDownloadUrl': instance.androidDownloadUrl,
      'admittanceUrl': instance.admittanceUrl,
      'credentialStuffingUrl': instance.credentialStuffingUrl,
      'pushUserDataUrl': instance.pushUserDataUrl,
      'creditDataUrl': instance.creditDataUrl,
      'loanProductUrl': instance.loanProductUrl,
      'loanContractUrl': instance.loanContractUrl,
      'submitLoanUrl': instance.submitLoanUrl,
      'loanPreviewUrl': instance.loanPreviewUrl,
      'bankListUrl': instance.bankListUrl,
      'bindBankUrl': instance.bindBankUrl,
      'setDefaultBankUrl': instance.setDefaultBankUrl,
      'preBind': instance.preBind,
      'getBank': instance.getBank,
      'userLoanAmt': instance.userLoanAmt,
      'orderStatusUrl': instance.orderStatusUrl,
      'repayPlanUrl': instance.repayPlanUrl,
      'repayDetailsUrl': instance.repayDetailsUrl,
      'contractSignUrl': instance.contractSignUrl,
      'queryUserUrl': instance.queryUserUrl,
      'status': instance.status,
      'isHead': instance.isHead,
      'addBank': instance.addBank,
      'isSign': instance.isSign,
      'isReload': instance.isReload,
      'created': instance.created,
      'updated': instance.updated,
      'businessType': instance.businessType,
    };
